apiVersion: v1
kind: Service
metadata:
  name: editor-api
  namespace: api-architect
  labels:
    app.kubernetes.io/name: editor-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: api-architect
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8765
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: editor-api
    app.kubernetes.io/component: backend
